package com.ocean.dao;
import  com.ocean.pojo.UserInfo;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userInfo
     *
     * @mbggenerated
     */
    int insertSelective(com.ocean.pojo.UserInfo record);
    //这个方式我自己单独加的方法
    List findAllUser();
}